name: Deploy Flask Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # This indicates using the self-hosted runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust Python version as needed

      # Step 3: Install dependencies
      - name: Virtual env
        run: |
          sudo apt install python3.12-venv -y
          python -m venv venv
          source venv/bin/activate
          
      # Step 4: Run tests (optional but recommended)
      - name: Install Dependencies
        run: |
          python -m pip install -upgrade pip
          pip install -r requirements.txt  # Or any other test command you use

      - name: Run unittests
        run: |
          python3 -m unittest test_app.py

      # Step 5: Deploy the app (since it's the same VM, no SSH needed)
      - name: Deploy Flask Application
        run: |
          nohup python3 app.py &
          
          
