name: Deploy Flask application

on:
  push:
    branches:
      - main

jobs:
  dockerbuild:
    runs-on: ubuntu-latest  # This indicates using the self-hosted runner

    steps:          
      - name: Code Checkout
        uses: actions/checkout@v4 
      # Step 4: Run tests (optional but recommended)
      
      - name: Docker build
        run: docker build -t janardhanboyalla672/github-action-repository:latest .

      - name: Docker login
        uses: docker/login-action@v2
        with:
         username: ${{secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PWD}}

      - name: Push the image
        run: |
         docker push janardhanboyalla672/github-action-repository:latest

          
          
