name: Deploy Flask application

on:
  push:
    branches:
      - main

jobs:
  dockerbuild:
    runs-on: ubuntu-latest  # This indicates using the self-hosted runner

    steps:          
      - name: Code Checkout
      - uses: actions/checkout@v4 
      # Step 4: Run tests (optional but recommended)
      - name: Docker build
        run: |
        

      - name: Run unittests
        run: |
          python3 -m unittest test_app.py

      # Step 5: Deploy the app (since it's the same VM, no SSH needed)
      - name: Deploy Flask Application
        run: 
          
          
          
